//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanEMIServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoanEMIModel", Namespace="http://schemas.datacontract.org/2004/07/LoanApplicationWCFService.Models")]
    public partial class LoanEMIModel : object
    {
        
        private decimal EMIAmoutField;
        
        private System.Guid EMIIdField;
        
        private int EMINoField;
        
        private string EMIPaymentDateField;
        
        private System.Guid LoanIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal EMIAmout
        {
            get
            {
                return this.EMIAmoutField;
            }
            set
            {
                this.EMIAmoutField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid EMIId
        {
            get
            {
                return this.EMIIdField;
            }
            set
            {
                this.EMIIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EMINo
        {
            get
            {
                return this.EMINoField;
            }
            set
            {
                this.EMINoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMIPaymentDate
        {
            get
            {
                return this.EMIPaymentDateField;
            }
            set
            {
                this.EMIPaymentDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid LoanId
        {
            get
            {
                return this.LoanIdField;
            }
            set
            {
                this.LoanIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoanEMIServiceReference.ILoanEMIService")]
    public interface ILoanEMIService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoanEMIService/AddLoanEMI", ReplyAction="http://tempuri.org/ILoanEMIService/AddLoanEMIResponse")]
        System.Threading.Tasks.Task AddLoanEMIAsync(LoanEMIServiceReference.LoanEMIModel loanEMI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoanEMIService/UpdateLoanEMI", ReplyAction="http://tempuri.org/ILoanEMIService/UpdateLoanEMIResponse")]
        System.Threading.Tasks.Task UpdateLoanEMIAsync(LoanEMIServiceReference.LoanEMIModel loanEMI, System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoanEMIService/DeleteLoanEMI", ReplyAction="http://tempuri.org/ILoanEMIService/DeleteLoanEMIResponse")]
        System.Threading.Tasks.Task DeleteLoanEMIAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoanEMIService/GetAllLoansEMIs", ReplyAction="http://tempuri.org/ILoanEMIService/GetAllLoansEMIsResponse")]
        System.Threading.Tasks.Task<LoanEMIServiceReference.LoanEMIModel[]> GetAllLoansEMIsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoanEMIService/GetLoanEMIById", ReplyAction="http://tempuri.org/ILoanEMIService/GetLoanEMIByIdResponse")]
        System.Threading.Tasks.Task<LoanEMIServiceReference.LoanEMIModel> GetLoanEMIByIdAsync(System.Guid Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface ILoanEMIServiceChannel : LoanEMIServiceReference.ILoanEMIService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class LoanEMIServiceClient : System.ServiceModel.ClientBase<LoanEMIServiceReference.ILoanEMIService>, LoanEMIServiceReference.ILoanEMIService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public LoanEMIServiceClient() : 
                base(LoanEMIServiceClient.GetDefaultBinding(), LoanEMIServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ILoanEMIService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LoanEMIServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(LoanEMIServiceClient.GetBindingForEndpoint(endpointConfiguration), LoanEMIServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LoanEMIServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(LoanEMIServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LoanEMIServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(LoanEMIServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LoanEMIServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task AddLoanEMIAsync(LoanEMIServiceReference.LoanEMIModel loanEMI)
        {
            return base.Channel.AddLoanEMIAsync(loanEMI);
        }
        
        public System.Threading.Tasks.Task UpdateLoanEMIAsync(LoanEMIServiceReference.LoanEMIModel loanEMI, System.Guid id)
        {
            return base.Channel.UpdateLoanEMIAsync(loanEMI, id);
        }
        
        public System.Threading.Tasks.Task DeleteLoanEMIAsync(System.Guid id)
        {
            return base.Channel.DeleteLoanEMIAsync(id);
        }
        
        public System.Threading.Tasks.Task<LoanEMIServiceReference.LoanEMIModel[]> GetAllLoansEMIsAsync()
        {
            return base.Channel.GetAllLoansEMIsAsync();
        }
        
        public System.Threading.Tasks.Task<LoanEMIServiceReference.LoanEMIModel> GetLoanEMIByIdAsync(System.Guid Id)
        {
            return base.Channel.GetLoanEMIByIdAsync(Id);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ILoanEMIService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ILoanEMIService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:54073/WCFServices/LoanEMI/LoanEMIService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return LoanEMIServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ILoanEMIService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return LoanEMIServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ILoanEMIService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ILoanEMIService,
        }
    }
}
